services:
  - type: web
    name: smu-nexora-website
    runtime: python
    buildCommand: pip install -r backend/requirements.txt && cd frontend && npm install && npm run build
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT